cc_library(
    name = "app",
    hdrs = [
        "config.h",
        "command.h",
        "app.h",
    ],
    srcs = [
        "app.cpp",
        "cmd_ast.cpp",
        "cmd_help.cpp",
    ],
    visibility = ["//visibility:public"],
)