cc_library(
    name = "ast",
    hdrs = [
        "ast.h",
        "traversal/traversal.h",
    ],
    srcs = [
        "ast.cpp",
        "traversal/level_order.cpp",
    ],
    visibility = ["//visibility:public"],
)