cc_library(
    name = "ast",
    hdrs = [
        "ast.h",
        "traversal/traversal.h",
        "serializer/serializer.h",
    ],
    srcs = [
        "ast.cpp",
        "traversal/level_order.cpp",
        "traversal/pre_order.cpp",
        "traversal/post_order.cpp",
        "serializer/markdown_level_table.cpp",
        "serializer/graphviz.cpp",
        "serializer/array_square.cpp",
    ],
    visibility = ["//visibility:public"],
)